okta:
  oauth2:
    issuer: https://dev-83250362.okta.com/oauth2/default
#
# JDBC properties
#
spring:
  data:
    rest:
      basePath: /articleManagement
  datasource:
    url: jdbc:mysql://localhost:3306/ispace_dev?useSSL=false&serverTimezone=Europe/Dublin
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
